version: 2

builds:
  - builder: rust
    flags:
      - --release
      - --target
      - "{{ .Target }}"
    targets:
      - x86_64-unknown-linux-gnu
      # - x86_64-apple-darwin
      - x86_64-pc-windows-gnu
      - aarch64-unknown-linux-gnu
      # - aarch64-apple-darwin
    hooks:
      pre:
        - rustup default --force-non-host stable-{{ .Target }}

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - maintainer: "Rene Jochum <rene@jochum.dev>"
    file_name_template: "{{ .ConventionalFileName }}" # optional, better file names
    formats:
      - deb
      - apk
      - rpm

release:
  footer: >-

    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
